services:
  - type: web
    name: lootify-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn lootify.wsgi:application"
