# Generated by Django 3.1.12 on 2025-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootify_test', '0002_auto_20250306_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
